export const resumeData = [
  {
    title: "Frontend Development Notes",
    description:
      "Comprehensive notes on HTML, CSS, and JavaScript fundamentals for frontend development.",
    subject: "Computer Science",
    fileUrl: "https://example.com/frontend-notes-1.pdf",
    uploadedBy: "69d93362dc824572966bfe0f",
    downloadedBy: [],
    likes: [],
    downloads: Math.floor(Math.random() * 101),
    ratings: {
      average: Math.random() * 5,
      count: Math.floor(Math.random() * 50),
      details: [],
    },
    role: "student",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "Backend Development with Node.js",
    description:
      "Detailed notes on server-side development using Node.js, Express, and MongoDB.",
    subject: "Computer Science",
    fileUrl: "https://example.com/backend-notes-2.pdf",
    uploadedBy: "69d93362dc824572966bfe0f",
    downloadedBy: [],
    likes: [],
    downloads: Math.floor(Math.random() * 101),
    ratings: {
      average: Math.random() * 5,
      count: Math.floor(Math.random() * 50),
      details: [],
    },
    role: "student",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "AI and Machine Learning Basics",
    description:
      "Introduction to artificial intelligence concepts, algorithms, and practical applications.",
    subject: "Computer Science",
    fileUrl: "https://example.com/ai-notes-3.pdf",
    uploadedBy: "69d93362dc824572966bfe0f",
    downloadedBy: [],
    likes: [],
    downloads: Math.floor(Math.random() * 101),
    ratings: {
      average: Math.random() * 5,
      count: Math.floor(Math.random() * 50),
      details: [],
    },
    role: "student",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "Data Science with Python",
    description:
      "Notes covering data analysis, visualization, and statistical methods using Python libraries.",
    subject: "Computer Science",
    fileUrl: "https://example.com/data-science-notes-4.pdf",
    uploadedBy: "69d93362dc824572966bfe0f",
    downloadedBy: [],
    likes: [],
    downloads: Math.floor(Math.random() * 101),
    ratings: {
      average: Math.random() * 5,
      count: Math.floor(Math.random() * 50),
      details: [],
    },
    role: "student",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "UI/UX Design Principles",
    description:
      "Essential principles and best practices for user interface and user experience design.",
    subject: "Design",
    fileUrl: "https://example.com/ui-ux-notes-5.pdf",
    uploadedBy: "69d93362dc824572966bfe0f",
    downloadedBy: [],
    likes: [],
    downloads: Math.floor(Math.random() * 101),
    ratings: {
      average: Math.random() * 5,
      count: Math.floor(Math.random() * 50),
      details: [],
    },
    role: "student",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "Cybersecurity Fundamentals",
    description:
      "Core concepts in cybersecurity, including threats, defenses, and ethical hacking.",
    subject: "Computer Science",
    fileUrl: "https://example.com/cybersecurity-notes-6.pdf",
    uploadedBy: "69d93362dc824572966bfe0f",
    downloadedBy: [],
    likes: [],
    downloads: Math.floor(Math.random() * 101),
    ratings: {
      average: Math.random() * 5,
      count: Math.floor(Math.random() * 50),
      details: [],
    },
    role: "student",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "Mobile App Development",
    description:
      "Notes on developing mobile applications for iOS and Android platforms.",
    subject: "Computer Science",
    fileUrl: "https://example.com/mobile-dev-notes-7.pdf",
    uploadedBy: "69d93362dc824572966bfe0f",
    downloadedBy: [],
    likes: [],
    downloads: Math.floor(Math.random() * 101),
    ratings: {
      average: Math.random() * 5,
      count: Math.floor(Math.random() * 50),
      details: [],
    },
    role: "student",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "Database Management Systems",
    description:
      "Comprehensive guide to relational and NoSQL database design and management.",
    subject: "Computer Science",
    fileUrl: "https://example.com/database-notes-8.pdf",
    uploadedBy: "69d93362dc824572966bfe0f",
    downloadedBy: [],
    likes: [],
    downloads: Math.floor(Math.random() * 101),
    ratings: {
      average: Math.random() * 5,
      count: Math.floor(Math.random() * 50),
      details: [],
    },
    role: "student",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "Cloud Computing Concepts",
    description:
      "Introduction to cloud platforms, services, and deployment strategies.",
    subject: "Computer Science",
    fileUrl: "https://example.com/cloud-notes-9.pdf",
    uploadedBy: "69d93362dc824572966bfe0f",
    downloadedBy: [],
    likes: [],
    downloads: Math.floor(Math.random() * 101),
    ratings: {
      average: Math.random() * 5,
      count: Math.floor(Math.random() * 50),
      details: [],
    },
    role: "student",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "DevOps Practices",
    description:
      "Notes on continuous integration, deployment, and infrastructure automation.",
    subject: "Computer Science",
    fileUrl: "https://example.com/devops-notes-10.pdf",
    uploadedBy: "69d93362dc824572966bfe0f",
    downloadedBy: [],
    likes: [],
    downloads: Math.floor(Math.random() * 101),
    ratings: {
      average: Math.random() * 5,
      count: Math.floor(Math.random() * 50),
      details: [],
    },
    role: "student",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "Blockchain Technology",
    description:
      "Fundamentals of blockchain, cryptocurrencies, and decentralized applications.",
    subject: "Computer Science",
    fileUrl: "https://example.com/blockchain-notes-11.pdf",
    uploadedBy: "69d93362dc824572966bfe0f",
    downloadedBy: [],
    likes: [],
    downloads: Math.floor(Math.random() * 101),
    ratings: {
      average: Math.random() * 5,
      count: Math.floor(Math.random() * 50),
      details: [],
    },
    role: "student",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "Software Engineering Principles",
    description:
      "Core principles of software development, design patterns, and methodologies.",
    subject: "Computer Science",
    fileUrl: "https://example.com/software-eng-notes-12.pdf",
    uploadedBy: "69d93362dc824572966bfe0f",
    downloadedBy: [],
    likes: [],
    downloads: Math.floor(Math.random() * 101),
    ratings: {
      average: Math.random() * 5,
      count: Math.floor(Math.random() * 50),
      details: [],
    },
    role: "student",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "Web Development Frameworks",
    description:
      "Overview of popular web frameworks like React, Angular, and Vue.js.",
    subject: "Computer Science",
    fileUrl: "https://example.com/web-frameworks-notes-13.pdf",
    uploadedBy: "69d93362dc824572966bfe0f",
    downloadedBy: [],
    likes: [],
    downloads: Math.floor(Math.random() * 101),
    ratings: {
      average: Math.random() * 5,
      count: Math.floor(Math.random() * 50),
      details: [],
    },
    role: "student",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "Data Structures and Algorithms",
    description:
      "Essential data structures and algorithmic problem-solving techniques.",
    subject: "Computer Science",
    fileUrl: "https://example.com/dsa-notes-14.pdf",
    uploadedBy: "69d93362dc824572966bfe0f",
    downloadedBy: [],
    likes: [],
    downloads: Math.floor(Math.random() * 101),
    ratings: {
      average: Math.random() * 5,
      count: Math.floor(Math.random() * 50),
      details: [],
    },
    role: "student",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "Network Security",
    description:
      "Advanced concepts in network security, firewalls, and intrusion detection.",
    subject: "Computer Science",
    fileUrl: "https://example.com/network-security-notes-15.pdf",
    uploadedBy: "69d93362dc824572966bfe0f",
    downloadedBy: [],
    likes: [],
    downloads: Math.floor(Math.random() * 101),
    ratings: {
      average: Math.random() * 5,
      count: Math.floor(Math.random() * 50),
      details: [],
    },
    role: "student",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "Machine Learning Algorithms",
    description:
      "Detailed notes on supervised and unsupervised machine learning algorithms.",
    subject: "Computer Science",
    fileUrl: "https://example.com/ml-algorithms-notes-16.pdf",
    uploadedBy: "69d93362dc824572966bfe0f",
    downloadedBy: [],
    likes: [],
    downloads: Math.floor(Math.random() * 101),
    ratings: {
      average: Math.random() * 5,
      count: Math.floor(Math.random() * 50),
      details: [],
    },
    role: "student",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "Full Stack Development",
    description:
      "End-to-end development notes covering both frontend and backend technologies.",
    subject: "Computer Science",
    fileUrl: "https://example.com/fullstack-notes-17.pdf",
    uploadedBy: "69d93362dc824572966bfe0f",
    downloadedBy: [],
    likes: [],
    downloads: Math.floor(Math.random() * 101),
    ratings: {
      average: Math.random() * 5,
      count: Math.floor(Math.random() * 50),
      details: [],
    },
    role: "student",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "Big Data Technologies",
    description:
      "Introduction to big data tools like Hadoop, Spark, and data processing frameworks.",
    subject: "Computer Science",
    fileUrl: "https://example.com/bigdata-notes-18.pdf",
    uploadedBy: "69d93362dc824572966bfe0f",
    downloadedBy: [],
    likes: [],
    downloads: Math.floor(Math.random() * 101),
    ratings: {
      average: Math.random() * 5,
      count: Math.floor(Math.random() * 50),
      details: [],
    },
    role: "student",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "API Development and Design",
    description:
      "Best practices for designing and implementing RESTful APIs and microservices.",
    subject: "Computer Science",
    fileUrl: "https://example.com/api-notes-19.pdf",
    uploadedBy: "69d93362dc824572966bfe0f",
    downloadedBy: [],
    likes: [],
    downloads: Math.floor(Math.random() * 101),
    ratings: {
      average: Math.random() * 5,
      count: Math.floor(Math.random() * 50),
      details: [],
    },
    role: "student",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "Version Control with Git",
    description:
      "Comprehensive guide to Git, GitHub, and collaborative development workflows.",
    subject: "Computer Science",
    fileUrl: "https://example.com/git-notes-20.pdf",
    uploadedBy: "69d93362dc824572966bfe0f",
    downloadedBy: [],
    likes: [],
    downloads: Math.floor(Math.random() * 101),
    ratings: {
      average: Math.random() * 5,
      count: Math.floor(Math.random() * 50),
      details: [],
    },
    role: "student",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "Computer Vision",
    description:
      "Notes on image processing, object detection, and computer vision applications.",
    subject: "Computer Science",
    fileUrl: "https://example.com/cv-notes-21.pdf",
    uploadedBy: "69d93362dc824572966bfe0f",
    downloadedBy: [],
    likes: [],
    downloads: Math.floor(Math.random() * 101),
    ratings: {
      average: Math.random() * 5,
      count: Math.floor(Math.random() * 50),
      details: [],
    },
    role: "student",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "Natural Language Processing",
    description:
      "Fundamentals of NLP, text analysis, and language model development.",
    subject: "Computer Science",
    fileUrl: "https://example.com/nlp-notes-22.pdf",
    uploadedBy: "69d93362dc824572966bfe0f",
    downloadedBy: [],
    likes: [],
    downloads: Math.floor(Math.random() * 101),
    ratings: {
      average: Math.random() * 5,
      count: Math.floor(Math.random() * 50),
      details: [],
    },
    role: "student",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "Microservices Architecture",
    description:
      "Design patterns and implementation strategies for microservices-based systems.",
    subject: "Computer Science",
    fileUrl: "https://example.com/microservices-notes-23.pdf",
    uploadedBy: "69d93362dc824572966bfe0f",
    downloadedBy: [],
    likes: [],
    downloads: Math.floor(Math.random() * 101),
    ratings: {
      average: Math.random() * 5,
      count: Math.floor(Math.random() * 50),
      details: [],
    },
    role: "student",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "Agile Development Methodologies",
    description:
      "Scrum, Kanban, and other agile practices for software development teams.",
    subject: "Computer Science",
    fileUrl: "https://example.com/agile-notes-24.pdf",
    uploadedBy: "69d93362dc824572966bfe0f",
    downloadedBy: [],
    likes: [],
    downloads: Math.floor(Math.random() * 101),
    ratings: {
      average: Math.random() * 5,
      count: Math.floor(Math.random() * 50),
      details: [],
    },
    role: "student",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "Containerization with Docker",
    description:
      "Docker fundamentals, container orchestration, and deployment strategies.",
    subject: "Computer Science",
    fileUrl: "https://example.com/docker-notes-25.pdf",
    uploadedBy: "69d93362dc824572966bfe0f",
    downloadedBy: [],
    likes: [],
    downloads: Math.floor(Math.random() * 101),
    ratings: {
      average: Math.random() * 5,
      count: Math.floor(Math.random() * 50),
      details: [],
    },
    role: "student",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "Testing and Quality Assurance",
    description:
      "Unit testing, integration testing, and QA best practices for software development.",
    subject: "Computer Science",
    fileUrl: "https://example.com/testing-notes-26.pdf",
    uploadedBy: "69d93362dc824572966bfe0f",
    downloadedBy: [],
    likes: [],
    downloads: Math.floor(Math.random() * 101),
    ratings: {
      average: Math.random() * 5,
      count: Math.floor(Math.random() * 50),
      details: [],
    },
    role: "student",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "Performance Optimization",
    description:
      "Techniques for optimizing application performance, scalability, and efficiency.",
    subject: "Computer Science",
    fileUrl: "https://example.com/performance-notes-27.pdf",
    uploadedBy: "69d93362dc824572966bfe0f",
    downloadedBy: [],
    likes: [],
    downloads: Math.floor(Math.random() * 101),
    ratings: {
      average: Math.random() * 5,
      count: Math.floor(Math.random() * 50),
      details: [],
    },
    role: "student",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "Ethical Hacking",
    description:
      "Introduction to penetration testing, vulnerability assessment, and ethical hacking.",
    subject: "Computer Science",
    fileUrl: "https://example.com/ethical-hacking-notes-28.pdf",
    uploadedBy: "69d93362dc824572966bfe0f",
    downloadedBy: [],
    likes: [],
    downloads: Math.floor(Math.random() * 101),
    ratings: {
      average: Math.random() * 5,
      count: Math.floor(Math.random() * 50),
      details: [],
    },
    role: "student",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "Game Development",
    description:
      "Fundamentals of game design, graphics programming, and game engine usage.",
    subject: "Computer Science",
    fileUrl: "https://example.com/game-dev-notes-29.pdf",
    uploadedBy: "69d93362dc824572966bfe0f",
    downloadedBy: [],
    likes: [],
    downloads: Math.floor(Math.random() * 101),
    ratings: {
      average: Math.random() * 5,
      count: Math.floor(Math.random() * 50),
      details: [],
    },
    role: "student",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "Internet of Things (IoT)",
    description:
      "IoT concepts, sensor networks, and embedded systems development.",
    subject: "Computer Science",
    fileUrl: "https://example.com/iot-notes-30.pdf",
    uploadedBy: "69d93362dc824572966bfe0f",
    downloadedBy: [],
    likes: [],
    downloads: Math.floor(Math.random() * 101),
    ratings: {
      average: Math.random() * 5,
      count: Math.floor(Math.random() * 50),
      details: [],
    },
    role: "student",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "Quantum Computing",
    description:
      "Introduction to quantum algorithms, qubits, and quantum computing principles.",
    subject: "Computer Science",
    fileUrl: "https://example.com/quantum-notes-31.pdf",
    uploadedBy: "69d93362dc824572966bfe0f",
    downloadedBy: [],
    likes: [],
    downloads: Math.floor(Math.random() * 101),
    ratings: {
      average: Math.random() * 5,
      count: Math.floor(Math.random() * 50),
      details: [],
    },
    role: "student",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "Augmented Reality Development",
    description:
      "AR development techniques, frameworks, and real-world applications.",
    subject: "Computer Science",
    fileUrl: "https://example.com/ar-notes-32.pdf",
    uploadedBy: "69d93362dc824572966bfe0f",
    downloadedBy: [],
    likes: [],
    downloads: Math.floor(Math.random() * 101),
    ratings: {
      average: Math.random() * 5,
      count: Math.floor(Math.random() * 50),
      details: [],
    },
    role: "student",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "Virtual Reality Applications",
    description:
      "VR technology, 3D modeling, and immersive experience development.",
    subject: "Computer Science",
    fileUrl: "https://example.com/vr-notes-33.pdf",
    uploadedBy: "69d93362dc824572966bfe0f",
    downloadedBy: [],
    likes: [],
    downloads: Math.floor(Math.random() * 101),
    ratings: {
      average: Math.random() * 5,
      count: Math.floor(Math.random() * 50),
      details: [],
    },
    role: "student",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "Robotics and Automation",
    description:
      "Robotics fundamentals, control systems, and industrial automation.",
    subject: "Computer Science",
    fileUrl: "https://example.com/robotics-notes-34.pdf",
    uploadedBy: "69d93362dc824572966bfe0f",
    downloadedBy: [],
    likes: [],
    downloads: Math.floor(Math.random() * 101),
    ratings: {
      average: Math.random() * 5,
      count: Math.floor(Math.random() * 50),
      details: [],
    },
    role: "student",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "Bioinformatics",
    description:
      "Computational methods for analyzing biological data and genomic sequences.",
    subject: "Biology",
    fileUrl: "https://example.com/bioinformatics-notes-35.pdf",
    uploadedBy: "69d93362dc824572966bfe0f",
    downloadedBy: [],
    likes: [],
    downloads: Math.floor(Math.random() * 101),
    ratings: {
      average: Math.random() * 5,
      count: Math.floor(Math.random() * 50),
      details: [],
    },
    role: "student",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "Financial Technology (FinTech)",
    description:
      "Blockchain in finance, payment systems, and digital banking innovations.",
    subject: "Economics",
    fileUrl: "https://example.com/fintech-notes-36.pdf",
    uploadedBy: "69d93362dc824572966bfe0f",
    downloadedBy: [],
    likes: [],
    downloads: Math.floor(Math.random() * 101),
    ratings: {
      average: Math.random() * 5,
      count: Math.floor(Math.random() * 50),
      details: [],
    },
    role: "student",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "Digital Marketing",
    description:
      "SEO, social media marketing, and digital advertising strategies.",
    subject: "Business",
    fileUrl: "https://example.com/digital-marketing-notes-37.pdf",
    uploadedBy: "69d93362dc824572966bfe0f",
    downloadedBy: [],
    likes: [],
    downloads: Math.floor(Math.random() * 101),
    ratings: {
      average: Math.random() * 5,
      count: Math.floor(Math.random() * 50),
      details: [],
    },
    role: "student",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "E-commerce Development",
    description:
      "Building online stores, payment integration, and e-commerce platforms.",
    subject: "Business",
    fileUrl: "https://example.com/ecommerce-notes-38.pdf",
    uploadedBy: "69d93362dc824572966bfe0f",
    downloadedBy: [],
    likes: [],
    downloads: Math.floor(Math.random() * 101),
    ratings: {
      average: Math.random() * 5,
      count: Math.floor(Math.random() * 50),
      details: [],
    },
    role: "student",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "Supply Chain Management",
    description:
      "Logistics, inventory management, and supply chain optimization techniques.",
    subject: "Business",
    fileUrl: "https://example.com/supply-chain-notes-39.pdf",
    uploadedBy: "69d93362dc824572966bfe0f",
    downloadedBy: [],
    likes: [],
    downloads: Math.floor(Math.random() * 101),
    ratings: {
      average: Math.random() * 5,
      count: Math.floor(Math.random() * 50),
      details: [],
    },
    role: "student",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "Human-Computer Interaction",
    description:
      "User-centered design, usability testing, and interaction design principles.",
    subject: "Design",
    fileUrl: "https://example.com/hci-notes-40.pdf",
    uploadedBy: "69d93362dc824572966bfe0f",
    downloadedBy: [],
    likes: [],
    downloads: Math.floor(Math.random() * 101),
    ratings: {
      average: Math.random() * 5,
      count: Math.floor(Math.random() * 50),
      details: [],
    },
    role: "student",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "Graphic Design Fundamentals",
    description:
      "Color theory, typography, composition, and digital design tools.",
    subject: "Design",
    fileUrl: "https://example.com/graphic-design-notes-41.pdf",
    uploadedBy: "69d93362dc824572966bfe0f",
    downloadedBy: [],
    likes: [],
    downloads: Math.floor(Math.random() * 101),
    ratings: {
      average: Math.random() * 5,
      count: Math.floor(Math.random() * 50),
      details: [],
    },
    role: "student",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "Animation and Multimedia",
    description:
      "2D/3D animation techniques, video editing, and multimedia production.",
    subject: "Design",
    fileUrl: "https://example.com/animation-notes-42.pdf",
    uploadedBy: "69d93362dc824572966bfe0f",
    downloadedBy: [],
    likes: [],
    downloads: Math.floor(Math.random() * 101),
    ratings: {
      average: Math.random() * 5,
      count: Math.floor(Math.random() * 50),
      details: [],
    },
    role: "student",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "Environmental Science",
    description:
      "Climate change, sustainability, and environmental conservation strategies.",
    subject: "Environmental Science",
    fileUrl: "https://example.com/environmental-notes-43.pdf",
    uploadedBy: "69d93362dc824572966bfe0f",
    downloadedBy: [],
    likes: [],
    downloads: Math.floor(Math.random() * 101),
    ratings: {
      average: Math.random() * 5,
      count: Math.floor(Math.random() * 50),
      details: [],
    },
    role: "student",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "Renewable Energy Systems",
    description:
      "Solar, wind, and other renewable energy technologies and implementation.",
    subject: "Engineering",
    fileUrl: "https://example.com/renewable-energy-notes-44.pdf",
    uploadedBy: "69d93362dc824572966bfe0f",
    downloadedBy: [],
    likes: [],
    downloads: Math.floor(Math.random() * 101),
    ratings: {
      average: Math.random() * 5,
      count: Math.floor(Math.random() * 50),
      details: [],
    },
    role: "student",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "Mechanical Engineering Design",
    description: "CAD, prototyping, and mechanical system design principles.",
    subject: "Engineering",
    fileUrl: "https://example.com/mechanical-eng-notes-45.pdf",
    uploadedBy: "69d93362dc824572966bfe0f",
    downloadedBy: [],
    likes: [],
    downloads: Math.floor(Math.random() * 101),
    ratings: {
      average: Math.random() * 5,
      count: Math.floor(Math.random() * 50),
      details: [],
    },
    role: "student",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "Electrical Engineering Fundamentals",
    description:
      "Circuit analysis, power systems, and electronic device principles.",
    subject: "Engineering",
    fileUrl: "https://example.com/electrical-eng-notes-46.pdf",
    uploadedBy: "69d93362dc824572966bfe0f",
    downloadedBy: [],
    likes: [],
    downloads: Math.floor(Math.random() * 101),
    ratings: {
      average: Math.random() * 5,
      count: Math.floor(Math.random() * 50),
      details: [],
    },
    role: "student",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "Civil Engineering Structures",
    description:
      "Structural analysis, building design, and construction engineering.",
    subject: "Engineering",
    fileUrl: "https://example.com/civil-eng-notes-47.pdf",
    uploadedBy: "69d93362dc824572966bfe0f",
    downloadedBy: [],
    likes: [],
    downloads: Math.floor(Math.random() * 101),
    ratings: {
      average: Math.random() * 5,
      count: Math.floor(Math.random() * 50),
      details: [],
    },
    role: "student",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "Chemical Engineering Processes",
    description:
      "Process design, reaction engineering, and industrial chemical processes.",
    subject: "Engineering",
    fileUrl: "https://example.com/chemical-eng-notes-48.pdf",
    uploadedBy: "69d93362dc824572966bfe0f",
    downloadedBy: [],
    likes: [],
    downloads: Math.floor(Math.random() * 101),
    ratings: {
      average: Math.random() * 5,
      count: Math.floor(Math.random() * 50),
      details: [],
    },
    role: "student",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "Aerospace Engineering",
    description:
      "Aircraft design, propulsion systems, and aerospace technology fundamentals.",
    subject: "Engineering",
    fileUrl: "https://example.com/aerospace-notes-49.pdf",
    uploadedBy: "69d93362dc824572966bfe0f",
    downloadedBy: [],
    likes: [],
    downloads: Math.floor(Math.random() * 101),
    ratings: {
      average: Math.random() * 5,
      count: Math.floor(Math.random() * 50),
      details: [],
    },
    role: "student",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "Biomedical Engineering",
    description:
      "Medical devices, biomechanics, and healthcare technology innovations.",
    subject: "Engineering",
    fileUrl: "https://example.com/biomedical-notes-50.pdf",
    uploadedBy: "69d93362dc824572966bfe0f",
    downloadedBy: [],
    likes: [],
    downloads: Math.floor(Math.random() * 101),
    ratings: {
      average: Math.random() * 5,
      count: Math.floor(Math.random() * 50),
      details: [],
    },
    role: "student",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
